### PR TITLE
mmmm[bt#2][t17]t18[bt#1 Update README.md vv

### PR DESCRIPTION
**Pull request by BT-scchmid-test**
<div> Links to Odoo: </div> <ul>
<li><a target="_blank" href="http://internal_v12.localhost/web#view_type=form&model=helpdesk.ticket&id=2">[bt#2] test</a></li>
</ul>

### CODE REVIEW

**Review by bt-sschmid-admin — APPROVED** [review]

**Review by BT-scchmid-test — COMMENTED** [review]
m

**Review by bt-sschmid-admin — APPROVED** [review]

**Review by BT-scchmid-test — COMMENTED** [review]
aa

**Comment by BT-scchmid-test** [comment]
dewd

**Comment by BT-scchmid-test** [comment]
qqqqqqqqqqqqqqqqqq

**Pull request merged**
